/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRetentionRouteImport } from './routes/_authenticated/retention'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAlterarSenhaRouteImport } from './routes/_authenticated/alterar-senha'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedCadastroUsuarioRouteImport } from './routes/_authenticated/cadastro.usuario'
import { Route as AuthenticatedCadastroTipoDocumentoRouteImport } from './routes/_authenticated/cadastro.tipo-documento'
import { Route as AuthenticatedCadastroEmpresaRouteImport } from './routes/_authenticated/cadastro.empresa'
import { Route as ApiPublicFilesIdRouteImport } from './routes/api/public/files/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetentionRoute = AuthenticatedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlterarSenhaRoute =
  AuthenticatedAlterarSenhaRouteImport.update({
    id: '/alterar-senha',
    path: '/alterar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastroUsuarioRoute =
  AuthenticatedCadastroUsuarioRouteImport.update({
    id: '/cadastro/usuario',
    path: '/cadastro/usuario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastroTipoDocumentoRoute =
  AuthenticatedCadastroTipoDocumentoRouteImport.update({
    id: '/cadastro/tipo-documento',
    path: '/cadastro/tipo-documento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastroEmpresaRoute =
  AuthenticatedCadastroEmpresaRouteImport.update({
    id: '/cadastro/empresa',
    path: '/cadastro/empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFilesIdRoute = ApiPublicFilesIdRouteImport.update({
  id: '/api/public/files/$id',
  path: '/api/public/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alterar-senha': typeof AuthenticatedAlterarSenhaRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/cadastro/empresa': typeof AuthenticatedCadastroEmpresaRoute
  '/cadastro/tipo-documento': typeof AuthenticatedCadastroTipoDocumentoRoute
  '/cadastro/usuario': typeof AuthenticatedCadastroUsuarioRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/files/$id': typeof ApiPublicFilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alterar-senha': typeof AuthenticatedAlterarSenhaRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/cadastro/empresa': typeof AuthenticatedCadastroEmpresaRoute
  '/cadastro/tipo-documento': typeof AuthenticatedCadastroTipoDocumentoRoute
  '/cadastro/usuario': typeof AuthenticatedCadastroUsuarioRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/files/$id': typeof ApiPublicFilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alterar-senha': typeof AuthenticatedAlterarSenhaRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/retention': typeof AuthenticatedRetentionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/_authenticated/cadastro/empresa': typeof AuthenticatedCadastroEmpresaRoute
  '/_authenticated/cadastro/tipo-documento': typeof AuthenticatedCadastroTipoDocumentoRoute
  '/_authenticated/cadastro/usuario': typeof AuthenticatedCadastroUsuarioRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/files/$id': typeof ApiPublicFilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/alterar-senha'
    | '/audit'
    | '/credits'
    | '/dashboard'
    | '/queue'
    | '/retention'
    | '/settings'
    | '/templates'
    | '/upload'
    | '/workflow'
    | '/cadastro/empresa'
    | '/cadastro/tipo-documento'
    | '/cadastro/usuario'
    | '/documents/$id'
    | '/documents/'
    | '/api/public/files/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/alterar-senha'
    | '/audit'
    | '/credits'
    | '/dashboard'
    | '/queue'
    | '/retention'
    | '/settings'
    | '/templates'
    | '/upload'
    | '/workflow'
    | '/cadastro/empresa'
    | '/cadastro/tipo-documento'
    | '/cadastro/usuario'
    | '/documents/$id'
    | '/documents'
    | '/api/public/files/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/alterar-senha'
    | '/_authenticated/audit'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/queue'
    | '/_authenticated/retention'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/upload'
    | '/_authenticated/workflow'
    | '/_authenticated/cadastro/empresa'
    | '/_authenticated/cadastro/tipo-documento'
    | '/_authenticated/cadastro/usuario'
    | '/_authenticated/documents/$id'
    | '/_authenticated/documents/'
    | '/api/public/files/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicFilesIdRoute: typeof ApiPublicFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retention': {
      id: '/_authenticated/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthenticatedRetentionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alterar-senha': {
      id: '/_authenticated/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AuthenticatedAlterarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastro/usuario': {
      id: '/_authenticated/cadastro/usuario'
      path: '/cadastro/usuario'
      fullPath: '/cadastro/usuario'
      preLoaderRoute: typeof AuthenticatedCadastroUsuarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastro/tipo-documento': {
      id: '/_authenticated/cadastro/tipo-documento'
      path: '/cadastro/tipo-documento'
      fullPath: '/cadastro/tipo-documento'
      preLoaderRoute: typeof AuthenticatedCadastroTipoDocumentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastro/empresa': {
      id: '/_authenticated/cadastro/empresa'
      path: '/cadastro/empresa'
      fullPath: '/cadastro/empresa'
      preLoaderRoute: typeof AuthenticatedCadastroEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/files/$id': {
      id: '/api/public/files/$id'
      path: '/api/public/files/$id'
      fullPath: '/api/public/files/$id'
      preLoaderRoute: typeof ApiPublicFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlterarSenhaRoute: typeof AuthenticatedAlterarSenhaRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedRetentionRoute: typeof AuthenticatedRetentionRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedCadastroEmpresaRoute: typeof AuthenticatedCadastroEmpresaRoute
  AuthenticatedCadastroTipoDocumentoRoute: typeof AuthenticatedCadastroTipoDocumentoRoute
  AuthenticatedCadastroUsuarioRoute: typeof AuthenticatedCadastroUsuarioRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlterarSenhaRoute: AuthenticatedAlterarSenhaRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedRetentionRoute: AuthenticatedRetentionRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedCadastroEmpresaRoute: AuthenticatedCadastroEmpresaRoute,
  AuthenticatedCadastroTipoDocumentoRoute:
    AuthenticatedCadastroTipoDocumentoRoute,
  AuthenticatedCadastroUsuarioRoute: AuthenticatedCadastroUsuarioRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicFilesIdRoute: ApiPublicFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
