ALTER TABLE public.organizations
  ADD COLUMN IF NOT EXISTS ai_price_base_threshold INTEGER NOT NULL DEFAULT 1100,
  ADD COLUMN IF NOT EXISTS ai_price_tier_step INTEGER NOT NULL DEFAULT 500,
  ADD COLUMN IF NOT EXISTS ai_price_tier_increment NUMERIC(10,4) NOT NULL DEFAULT 0.01;